name: 'Cloudflared SSH'
description: 'Setup for SSH via cloudflared tunnel'
author: 'Fakeapate'
inputs:
  ssh_private_key:
      description: 'SSH Private Key'
      required: true
  ssh_remote_host:
      description: 'SSH Host'
      required: true
  cloudflared_id:
      description: 'Cloudflared Service Token Id'
      required: true
  cloudflared_secret:
      description: 'Cloudflared Service Token Secret'
      required: true
runs:
  using: "composite"
  steps:
    - name: Install cloudflare
      shell: bash
      run: |
        curl -L "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64" -o cloudflared
        sudo chmod +x cloudflared
        sudo mv cloudflared /usr/local/bin/cloudflared

    - name: Set up SSH Key
      shell: bash
      env:
        SSH_PRIVATE_KEY: ${{ inputs.ssh_private_key }}
      run: |
        mkdir -p ~/.ssh
        echo "${SSH_PRIVATE_KEY}" | base64 --decode > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

    - name: Setup SSH Config
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo "Host ${{ inputs.ssh_remote_host }}" >> ~/.ssh/config
        echo "  IdentityAgent none" >> ~/.ssh/config
        echo "  IdentityFile ~/.ssh/id_ed25519" >> ~/.ssh/config
        echo "  StrictHostKeyChecking no" >> ~/.ssh/config
        echo "  UserKnownHostsFile /dev/null" >> ~/.ssh/config
        echo "  ProxyCommand /usr/local/bin/cloudflared access ssh --id ${{ inputs.cloudflared_id }} --secret ${{ inputs.cloudflared_secret }} --hostname %h" >> ~/.ssh/config
        chmod 600 ~/.ssh/config
        chmod 700 ~/.ssh
        
