name: Test Action

on:
  workflow_dispatch:
env:
  DOCKER_HOST: "ssh://${{ vars.SSH_REMOTE_USER }}@${{ vars.SSH_REMOTE_HOST }}"
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SSH_REMOTE_HOST: ${{ vars.SSH_REMOTE_HOST }}
  CLOUDFLARED_ID: ${{ secrets.CLOUDFLARED_ID }}
  CLOUDFLARED_SECRET: ${{ secrets.CLOUDFLARED_SECRET }}

defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Action
        uses: RedNoodlesOrg/rednet-actions-cloudflared-ssh@main
      - name: Docker
        id: docker
        run: |
          docker ps
