name: Test Action

on:
  workflow_dispatch:
env:
  DOCKER_HOST: "ssh://${{ vars.SSH_REMOTE_USER }}@${{ vars.SSH_REMOTE_HOST }}"
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Action
        uses: RedNoodlesOrg/rednet-actions-cloudflared-ssh@main
      - name: Docker
        id: docker
        run: |
          docker ps
